{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-mystery-stew
  version: {{ version }}

source:
  path: ../..

build:
  script: make install
requirements:
  host:
    - python  {{ python }}
    - setuptools

  run:
    - python  {{ python }}
    - qiime2 {{ release }}.*

test:
  imports:
    - q2_mystery_stew

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
