{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-mystery-stew
  version: {{ version }}

source:
  path: ../..

build:
  script: make install
requirements:
  host:
    - python  {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - pytest

  imports:
    - q2_mystery_stew

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
